### ISSUE TITLE
Whitespace issue in startup scripts

### ISSUE THREAD

**Issue by bernd** [Graylog2/collector#28]
There seems to be an issue with blanks in directories.

```
c:\test test\graylog-collector-0.2.2\bin>graylog-collector-service.bat start GraylogCollector
The data area passed to a system call is too small. Failed to start service
ERROR: Failed to start service: GraylogCollector
```

**Comment by manhdinh** [comment]
Hello, i have the shame issue with this bug, pls help me what is the problem in here and how to fix it?

**Comment by joschi** [comment]
@manhdinh Which version of the Graylog Collector are you using? This problem should've been in Graylog Collector 0.2.4 and higher.

**Comment by manhdinh** [comment]
Oh, i realize that it seem be a wrong configuration with the java :D

**Comment by manhdinh** [comment]
Hello, my problem in winserver seems to be a wrong configuration and i fixed it. But i have another problems while i config collector in Ubuntu 14.04 . I follow  http://docs.graylog.org/en/1.2/pages/collector.html and after i run collector, the logs like that: http://prntscr.com/9akrer     I think everything ok but i can't see my machine in web interface http://prntscr.com/9aktp8
I have set java parameters like that : http://prntscr.com/9aktaj , i quite confuse because the java has 2 type?
This is my collector.conf : http://prntscr.com/9akrtl

**Comment by joschi** [comment]
@manhdinh Please post your problem to [our mailing list](https://groups.google.com/forum/#!forum/graylog2) or [join #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog). The GitHub issue tracker is reserved for bug reports and feature requests.

**Comment by manhdinh** [comment]
okay, thank you !
