### ISSUE TITLE
java embedded installer

### ISSUE THREAD

**Issue by andreaconsadori** [Graylog2/collector#30]
create an executable installer with embedded java
actually manual install is an heavy task and i cannot download 130 mb of java jdk per client

**Comment by bernd** [comment]
We will consider embedding a JRE for the windows packages. If we will actually do it depends on the redistribution situation which we have to investigate carefully.

We are not going to bundle a JRE for the Linux packages because installing a JRE on Linux is pretty easy.

See the following feature request and issues regarding Windows and Linux packages.

* https://graylog.ideas.aha.io/ideas/GL2E-I-396
* https://github.com/Graylog2/collector/issues/18
* https://github.com/Graylog2/collector/issues/32
