### ISSUE TITLE
Missing Log-File is not configuration error

### ISSUE THREAD

**Issue by trobers** [Graylog2/collector#33]
We use a lot of applications, that write logs only in case of error. In the consequence there is not a log all the time. But in this case the collector wont start. 

Example error-message: 

2015-06-18T09:52:27.376+0200 ERROR [main] cli.commands.Run - Configuration Error: /var/log/apache2/access.log or /var/log/apache2 is not accessible (check if directory exists and permissions are correct) (path)

It is possible to change this behaviour of the collector? The collector could poll in intervall if the log exists.

**Comment by bernd** [comment]
Yes, we have been a bit on the fence regarding this check. We will make the check a warning instead of a hard error to alert the user for potential misconfiguration but still allow a delayed creation of the file.

The collector is watching the directory already and gets notified once a file comes into existence.

**Comment by bernd** [comment]
Fixed in v0.2.3. (https://packages.graylog2.org/releases/graylog-collector/graylog-collector-0.2.3.tgz)
