### ISSUE TITLE
Hostname from same Host not the same in Type=file and Type=windows-eventlog

### ISSUE THREAD

**Issue by renapu** [Graylog2/collector#68]
Hi,

Idk why, but on the same Host the Hostname is not the same in Graylog.
The collector runs on a Windows-Server 2k12 Machine.
We collect file based logs and Eventlog based logs.

With type=file => source:dc01
With type=windows-eventlog => source: dc01.domain.local

**Comment by joschi** [comment]
@renapu Please post your Graylog Collector configuration file and the configuration of your GELF Input in Graylog.

**Comment by renapu** [comment]
server-url = "http://syslog.domain.local:12900"

enable-registration = true

collector-id = "file:config/collector-id"
inputs {
  syslog {
    type = "file"
    path = "C:\\Logs\\DNS_GreyLog.log"
	reader-interval = "1s"
	content-splitter = "PATTERN"
	content-splitter-pattern = "^\\d{2}.\\d{2}.\\d{4}"
	message-fields = {
      "SourceModuleName" = "dns"
    }
  }
  win-eventlog-security{
	type = "windows-eventlog"
	source-name = "Security"
	poll-interval = "1s"
  }
  win-eventlog-system{
	type = "windows-eventlog"
	source-name = "System"
	poll-interval = "1s"
  }
}

outputs {
  gelf-udp {
    type = "gelf"
    host = "syslog.domain.local"
    port = 5414
  }
}

GELF input:
recv_buffer_size: 1048576
port: 5414
tls_key_file:
tls_key_password: *******
use_null_delimiter: true
tls_client_auth_cert_file:
max_message_size: 2097152
tls_client_auth: disabled
override_source:
bind_address: 192.168.100.20
tls_cert_file:

**Comment by joschi** [comment]
The file input is using [`InetAddress#getHostName()`](https://docs.oracle.com/javase/7/docs/api/java/net/InetAddress.html#getHostName()) under the hood (via [`Utils#getHostname()`](https://github.com/Graylog2/collector/blob/0.4.1/src/main/java/org/graylog/collector/utils/Utils.java#L34) in [`FileInput#doStart()`](https://github.com/Graylog2/collector/blob/0.4.1/src/main/java/org/graylog/collector/inputs/file/FileInput.java#L71)) while the Windows EventLog input is using the provided computer name (in [`WindowsEventlogHandler#handleNotification()`](https://github.com/Graylog2/collector/blob/0.4.1/src/main/java/org/graylog/collector/inputs/eventlog/WindowsEventlogHandler.java#L53)).

@bernd The simplest way to consolidate the source field would be to use [`InetAddress#getCanonicalHostName()`](https://docs.oracle.com/javase/7/docs/api/java/net/InetAddress.html#getCanonicalHostName()) in the `Utils` class to retrieve the FQDN instead of just the simple host name.
