### ISSUE TITLE
Unquoted service path privilege escalation vulnerability

### ISSUE THREAD

**Issue by joeylane** [Graylog2/collector#93]
On Windows, the Graylog Collector service path is unquoted.  This creates a potential privilege escalation vulnerability if a user were to install the service in a directory containing a space.

Surrounding the path with quotation marks during installation would correct this issue.

Users can also fix this themselves by going into the registry, and quoting the path manually after installation.

**Comment by joschi** [comment]
https://www.exploit-db.com/exploits/40538/

**Comment by bernd** [comment]
@joeylane Thank you for submitting the issue! :smiley:  We added a warning to the README in 93af261 that there are issues with quoting when installing as Windows service. Since we are using [procrun](https://commons.apache.org/proper/commons-daemon/procrun.html) to install the service, it looks like we do not have a way to fix the quoting of the path.

Fixing this would require us to replace procrun with something else and since we are no longer working on the Collector, we cannot afford the time unfortunately.

**Comment by joeylane** [comment]
No problem.  I understand Collector is a deprecated feature (Sidecar is awesome btw).  Just wanted to make others aware in case they hadn't upgraded from Graylog 1.x yet.  Keep up the awesome work, I use Graylog every day :)
